name: validate
on:
  push: 
    branches:
      - '*'
      - '*/*'
      - '**'
  pull_request:
    types: [opened, synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup node 
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'

      - name: Install deps
        run: npm install

      - name: Check types
        run: npm ts:check

      - name: Unit testing
        run: npm test
  
