name: validate
on:
  push: 
    branches:
      - '*'
      - '*/*'
      - '**'
  pull_request:
    types: [opened, synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup node 
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Check types
        run: yarn ts:check

      - name: Unit testing
        run: yarn test
  
